spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/week3
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

  datasource:
    url: jdbc:mysql://springboot-database.chh8aypxdyul.ap-northeast-2.rds.amazonaws.com:3306/hanghaeblog
    username: admin
    password: 1tjddls4
  jpa:
    hibernate:
      ddl-auto: create



logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

#  spring.datasource.url=jdbc:mysql://springboot-database.chh8aypxdyul.ap-northeast-2.rds.amazonaws.com:3306/springblog
#  spring.datasource.username=admin
#  spring.datasource.password=1tjddls4
#  spring.jpa.hibernate.ddl-auto=create